# services:
#   mongodatabase:
#     image: mongo
#     # container_name: mongo
#     ports:
#       - "27018:27017"

#   waveentry-backend:
#     image: wave-entry-server
#     # container_name: backend
#     environment:
#       - DB_HOST=mongodatabase
#       - DB_PORT=27018
#       - DB_NAME=waveentrydatabase
#       - SERVER_PORT=3001 # donot use 3000 here because 3000 will be used for ui
#       - JWT_SECRET=abcd1234
#     ports:
#       - 3001:3001
#     command:
#       - npm run db:seed
#     depends_on:
#       - mongodatabase

#   waveentry-frontend:
#     image: waveentry
#     ports:
#       - 3000:3000 # 3000 is exposed from the image dockerfile
#     environment:
#       - REACT_APP_SERVER_URL=http://waveentry-backend:3001
#     depends_on:
#       - mongodatabase
#       - waveentry-backend

services:
  mongodb:
    image: mongo
    restart: always

  backend:
    image: waveentry-server
    environment:
      - DB_HOST=mongodb
      - DB_NAME=wavedb
      - SERVER_PORT=3001
      - JWT_SECRET=abcd1234
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  seeder:
    image: waveentry-server
    environment:
      - DB_HOST=mongodb
      - DB_NAME=wavedb
      - SERVER_PORT=3001
      - JWT_SECRET=abcd1234
    command: npm run db:seed
    depends_on:
      - mongodb
      - backend

  frontend:
    image: waveentry-web
    environment:
      - REACT_APP_SERVER_URL=http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - backend
      - seeder
