services:
  mongodb:
    image: mongo
    restart: always

  backend:
    image: waveentry-server
    environment:
      - DB_HOST=mongodb
      - DB_NAME=wavedb
      - SERVER_PORT=3001
      - JWT_SECRET=abcd1234
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  seeder:
    image: waveentry-server
    environment:
      - DB_HOST=mongodb
      - DB_NAME=wavedb
      - SERVER_PORT=3001
      - JWT_SECRET=abcd1234
    command: npm run db:seed
    depends_on:
      - mongodb
      - backend

  frontend:
    image: waveentry-web
    environment:
      - REACT_APP_SERVER_URL=http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - backend
      - seeder
